/*
 OOOOOOOOOOOOOOOOOOOOOOOOOOBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSS:

"recommended approach in Next.js" 
layout.tsx //{ should }// remains a pure server component for better performance..   
*/

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeWrapper from '@/components/theme/theme-wrapper';
import Navbar from '@/components/layout/navbar';
import Footer from '@/components/layout/footer';
import PageContainer from '@/components/layout/page-container';
import Sidebar from '@/components/layout/sidebar';
import { Box } from '@mui/material';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeWrapper>
          <PageContainer>
            <Box
              sx={{
                display: 'flex',
                minHeight: '100vh',
                width: '100%',
              }}
            >
              <Sidebar />
              <Box
                component="main"
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  flexGrow: 1,
                  minHeight: '100vh',
                  position: 'relative',
                }}
              >
                <Navbar />
                <Box sx={{ flexGrow: 1, pb: '60px' }}>{children}</Box>
                <Footer />
              </Box>
            </Box>
          </PageContainer>
        </ThemeWrapper>
      </body>
    </html>
  );
}
